### ISSUE TITLE
Cannot find module 'package.json'

### ISSUE THREAD

**Issue by mafo5** [nyaayaya/package-version#3]
Hi,

Thanks for your Action.
Unfortunately, I ran into an error. 

First I got a strange behaviour. In one of [my repositories](https://github.com/mafo5/simpleAWS) I want to use your action to avoid using the commit SHA as an image tag. So I added your script in front of the AWS deploy script. It runs well but returns `0.0.0` as a version. (e.g. https://github.com/mafo5/simpleAWS/runs/819209430?check_suite_focus=true)

To not create a lot of commits in this repository I created another private repository and tried to set the `path` variable you mentioned in the documentation. So I tried this:
```
   - name: package-version
      uses: nyaascii/package-version@v1.0.0
      with:
        path: 'package.json'
```
Unfortunately, this resulted in the error `Cannot find module 'package.json'`.
Strangely when I run it in the private repository with the same AWS deploy script of my early mentions repository. It returns correctly the version. I am confused. 🤨

What am I doing wrong?

Greetings

**Comment by nyaa8** [comment]
Hello, and thank you for checking out my tiny Action!

Gahh, I am so sorry I didn't respond earlier. Somehow it didn't appear in my notifications :(
hmm, ~~it looks like I've messed up and used "absolute" `require()` 😢 Looks like I was wrong. Something strange is happening:~~
~~- Auto-finder's path: `./`~~
~~- Manual: `./package.json`~~

~~And node throws an exception for `./package.json`, not for `./`...~~

But why it returns `0.0.0`, huh.
That "auto-finding feature" uses `@actions/glob`, with this pattern: `['**/package.json', '!**/node_modules']`, so it should ignore all node_modules directories... 

I am currently trying to fix this. Again, I am deeply sorry about this issue. 🙇🏼‍♀️

**Comment by nyaa8** [comment]
Oopsie, GitHub closed it automatically 😓

**Comment by nyaa8** [comment]
@mafo5 Hii!
I think it's fixed now, could you try again, please? 😊

```yaml
- name: package-version
  uses: nyaascii/package-version@1.0.2-pre
```

Thank you 🙇🏼‍♀️

**Comment by mafo5** [comment]
Thank you!

the new version works without an error and my strange 0.0.0 problem is fixed by directly giving the `package.json` as an input. like:
```
- name: package-version
  uses: nyaascii/package-version@1.0.2-pre
    with:
    path: 'package.json'
```

**Comment by dgreene1** [comment]
I've never gotten this to work dependably even with the suggestions above and thus have moved to using https://github.com/Saionaro/extract-package-version

Perhaps @nyaa8 can look at that package to see what causes the flakiness. But I'm going to unsubscribe from the issue. Just wanted to share one that works dependably.
